services:
  # 后端API服务
  - type: web
    name: texas-poker-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production- key: PORT
        value:10000
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        fromService:
          type: web
          name: texas-poker-webenvVarKey: RENDER_EXTERNAL_URL# 前端静态网站
  - type: web
    name: texas-poker-web
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: texas-poker-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: REACT_APP_WS_URL
        fromService:
          type: web
          name: texas-poker-api
          envVarKey: RENDER_EXTERNAL_URL
